project:
  type: website
  output-dir: _site

website:
  title: "BioSUPERCAP"
  site-url: "https://biosupercap.com"
  description: "Official website of the BioSUPERCAP research project"

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: PI & Team
        href: team.qmd
      - text: Infrastructure
        href: infrastructure.qmd
      - text: Publications
        href: publications.qmd
      - text: News
        href: news.qmd
      - text: Contact
        href: contact.qmd

  page-footer:
    left: "Â© 2025 BioSUPERCAP"
    right: "Funded by Hellenic Foundation for Research & Innovation (Grant No. 25886)"

format:
  html:
    theme: cosmo
    css: styles/custom.css
    toc: true
